version: 0.0
files:
  - source: /index.html
    destination: /var/www/html

hooks:
  AfterInstall:
    - location: script/install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: script/Start.sh
      timeout: 300
      runas: root
