version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: script/i.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: script/start.sh
      timeout: 300
      runas: root
