version: 0.0
files:
  - source: /index.html
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: script/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: script/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: script/install_nginx.sh
      timeout: 300
      runas: root
