version: 0.0
files:
  - source: /index.html
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: script/install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: script/stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: script/start.sh
      timeout: 300
      runas: root
